use_frameworks!

platform :ios, '10.0'

target 'UIFadeLabel_Example' do
  pod 'UIFadeLabel', :path => '../'

  target 'UIFadeLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
